import './style.css';
import { CheckPortAvailable, CurrentHostsZone, FixNow, GetSettings, GetStartupDiff, ListDomains, ListForwards, Pause, PendingAction, QuitHost, Resume, SaveAll, SetAutoStart, SetSettings, SuggestFreePort } from '../wailsjs/go/main/App.js';
import { EventsOn, WindowShow, WindowUnminimise } from '../wailsjs/runtime/runtime.js';

const app = document.querySelector('#app');
const state = {
  domains: [], forwards: [], appliedDomains: [], appliedForwards: [], diff: null,
  settings: null, hostsZone: '', confirm: null, portIssues: {}, rowErrors: {},
  dirty: false, saving: false, loading: true, dnsSaveTimer: null, quitting: false,
};

const esc = (value = '') => String(value).replace(/[&<>'"]/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[c]));
const idOf = (item) => item.id == null || item.id === '' ? item.__draftId : String(item.id);
const port = (value) => { const n = Number(value); return Number.isFinite(n) ? n : 0; };
const copy = (items) => items.map((item) => ({ ...item, status: item.status ? { ...item.status } : undefined }));
const domainDTO = (item) => ({ ...(item.id ? { id: String(item.id) } : {}), domain: String(item.domain || '').trim() });
const forwardDTO = (item) => ({ ...(item.id ? { id: String(item.id) } : {}), listenPort: port(item.listenPort), targetHost: String(item.targetHost || '').trim(), targetPort: port(item.targetPort), enabled: !!item.enabled });
const same = (a, b) => JSON.stringify(domainDTO(a)) === JSON.stringify(domainDTO(b));
const sameForward = (a, b) => JSON.stringify(forwardDTO(a)) === JSON.stringify(forwardDTO(b));
const match = (items, item) => items.find((entry) => idOf(entry) === idOf(item));

function updateDirty() {
  state.dirty = state.domains.length !== state.appliedDomains.length || state.forwards.length !== state.appliedForwards.length
    || state.domains.some((item) => { const applied = match(state.appliedDomains, item); return !applied || !same(item, applied); })
    || state.forwards.some((item) => { const applied = match(state.appliedForwards, item); return !applied || !sameForward(item, applied); });
}
function changedCount() {
  const domains = state.domains.filter((item) => { const applied = match(state.appliedDomains, item); return !applied || !same(item, applied); }).length;
  const forwards = state.forwards.filter((item) => { const applied = match(state.appliedForwards, item); return !applied || !sameForward(item, applied); }).length;
  return domains + forwards + state.appliedDomains.filter((item) => !match(state.domains, item)).length + state.appliedForwards.filter((item) => !match(state.forwards, item)).length;
}
function pending(item, type) { const applied = match(type === 'domain' ? state.appliedDomains : state.appliedForwards, item); return !applied || (type === 'domain' ? !same(item, applied) : !sameForward(item, applied)); }
function toast(message, type = 'info') { const node = document.createElement('div'); node.className = `toast toast-${type}`; node.textContent = message; document.querySelector('#toasts').append(node); requestAnimationFrame(() => node.classList.add('visible')); setTimeout(() => { node.classList.remove('visible'); setTimeout(() => node.remove(), 180); }, 3000); }
function shell() {
  app.innerHTML = `<div class="topbar" aria-hidden="true"></div><main class="page"><header class="page-header"><div><h1>内网接管</h1><p class="subtitle">域名先回到本机,再转发到内网服务</p></div><div class="header-actions no-drag"><span id="pause-state" class="pause-state"></span><button class="button secondary pause-button" data-action="pause"></button><button class="icon-button" data-action="settings" aria-label="打开设置" title="设置">⚙</button></div></header><section id="banner"></section><section id="record-list" class="flow-list"></section><footer id="footer" class="statusbar"></footer></main><div id="overlay-root"></div><div id="toasts" class="toast-container" aria-live="polite"></div>`;
}
function statusText(status, paused) { if (paused) return '已暂停'; if (status.state === 'listening') return status.resolvedIP ? `监听中 · ${status.resolvedIP}` : '监听中'; if (status.state === 'error') return `异常: ${status.reason || '运行失败'}`; return '已停用'; }
function rowError(type, item) { return (state.rowErrors[`${type}:${idOf(item)}`] || []).filter((error) => !error.startsWith('回环风险') && !error.startsWith('特权端口')).map((error) => `<div class="inline-error">${esc(error)}</div>`).join(''); }
function warning(type, item) { return (state.rowErrors[`${type}:${idOf(item)}`] || []).filter((error) => error.startsWith('回环风险') || error.startsWith('特权端口')).map((error) => `<div class="inline-warning">${esc(error)}</div>`).join(''); }
function blockingError(type, item) { return (state.rowErrors[`${type}:${idOf(item)}`] || []).some((error) => !error.startsWith('回环风险') && !error.startsWith('特权端口')); }
function render() {
  const paused = !!state.settings?.paused;
  const pauseState = document.querySelector('#pause-state'); const pauseButton = document.querySelector('.pause-button');
  if (pauseState) { pauseState.textContent = paused ? '已暂停' : '托管中'; pauseState.className = `pause-state ${paused ? 'paused' : 'active'}`; pauseButton.textContent = paused ? '恢复托管' : '暂停托管'; pauseButton.dataset.action = paused ? 'resume' : 'pause'; }
  document.querySelector('#banner').innerHTML = `${paused ? '<div class="paused-banner"><span class="warning-icon">Ⅱ</span><span>托管已暂停:hosts 已清空,转发已停止</span></div>' : ''}${state.diff && !state.diff.consistent ? `<div class="warning-banner"><span class="warning-icon">!</span><span>hosts 与配置不一致,${state.diff.missingInHosts?.length || 0} 条配置未写入,${state.diff.missingInConfig?.length || 0} 条残留。</span><button class="button warning-button" data-action="fix">立即修复</button></div>` : ''}`;
  const domainRows = state.domains.map((item) => { const key = idOf(item); const bad = rowError('domain', item); return `<div class="edit-row domain-row ${pending(item, 'domain') ? 'pending' : ''} ${blockingError('domain', item) ? 'has-error' : ''}" data-type="domain" data-id="${esc(key)}"><input class="row-input domain-input" data-field="domain" data-id="${esc(key)}" value="${esc(item.domain)}" placeholder="例如 nas.example.com" aria-label="托管域名"><span class="loopback-hint">→ 127.0.0.1</span>${pending(item, 'domain') ? '<span class="pending-label">待应用</span>' : ''}<button class="remove-button" data-action="delete-domain" data-id="${esc(key)}" aria-label="删除域名" title="删除">×</button>${bad || warning('domain', item) ? `<div class="row-messages">${bad}${warning('domain', item)}</div>` : ''}</div>`; }).join('');
  const forwardRows = state.forwards.map((item) => { const key = idOf(item); const status = item.status || { state: 'stopped' }; const errors = rowError('forward', item); const issue = state.portIssues[key]; const portHint = issue ? `<div class="inline-error port-error">端口 ${issue.port} 已被占用,建议 ${issue.suggested || '其他端口'} <button class="suggest-button" data-action="suggest-port" data-id="${esc(key)}" data-port="${esc(issue.suggested || '')}">采用</button></div>` : ''; return `<div class="edit-row forward-row ${pending(item, 'forward') ? 'pending' : ''} ${blockingError('forward', item) ? 'has-error' : ''}" data-type="forward" data-id="${esc(key)}"><label class="check-wrap" title="${item.enabled ? '停用' : '启用'}"><input type="checkbox" data-field="enabled" data-id="${esc(key)}" ${item.enabled ? 'checked' : ''}><span></span></label><span class="port-prefix">:</span><input class="row-input port-input" data-field="listenPort" data-id="${esc(key)}" type="text" inputmode="numeric" pattern="[0-9]*" maxlength="5" value="${item.listenPort || ''}" aria-label="监听端口"><span class="route-arrow">→</span><input class="row-input host-input" data-field="targetHost" data-id="${esc(key)}" value="${esc(item.targetHost)}" placeholder="内网地址" aria-label="目标地址"><span class="port-separator">:</span><input class="row-input port-input" data-field="targetPort" data-id="${esc(key)}" type="text" inputmode="numeric" pattern="[0-9]*" maxlength="5" value="${item.targetPort || ''}" aria-label="目标端口"><span class="row-status ${paused ? 'paused' : status.state}"><i class="status-dot ${paused ? 'stopped' : esc(status.state)}"></i>${esc(statusText(status, paused))}</span>${pending(item, 'forward') ? '<span class="pending-label">待应用</span>' : ''}<button class="remove-button" data-action="delete-forward" data-id="${esc(key)}" aria-label="删除转发" title="删除">×</button><div class="row-messages">${errors}${warning('forward', item)}${portHint}</div></div>`; }).join('');
  const active = document.activeElement; const activeKey = active?.dataset?.id; const activeField = active?.dataset?.field; const selectionStart = active?.selectionStart; const selectionEnd = active?.selectionEnd;
  document.querySelector('#record-list').innerHTML = `<section class="flow-section"><div class="section-heading"><div><h2>托管域名 <span>${state.domains.length}</span></h2><p>这些域名都会解析到 127.0.0.1</p></div><button class="add-button" data-action="add-domain">＋ 添加</button></div><div class="section-rows">${domainRows || '<div class="section-empty">还没有托管域名</div>'}</div></section><section class="flow-section forwards-section"><div class="section-heading"><div><h2>端口转发 <span>${state.forwards.length}</span></h2><p>将本机端口连接到内网目标</p></div><button class="add-button" data-action="add-forward">＋ 添加</button></div><div class="section-rows">${forwardRows || '<div class="section-empty">还没有端口转发</div>'}</div></section>`;
  if (activeKey && activeField) { const restored = document.querySelector(`[data-id="${CSS.escape(activeKey)}"][data-field="${CSS.escape(activeField)}"]`); if (restored) { restored.focus(); if (selectionStart != null) restored.setSelectionRange?.(selectionStart, selectionEnd); } }
  const listening = state.forwards.filter((item) => item.status?.state === 'listening').length; const footer = document.querySelector('#footer'); footer.className = state.dirty ? 'dirty-footer' : 'statusbar'; footer.innerHTML = state.dirty ? `<span class="dirty-count">● ${changedCount()} 项未保存的更改</span><div class="footer-actions"><button class="button secondary" data-action="discard">放弃</button><button class="button primary" data-action="apply" ${state.saving ? 'disabled' : ''}>${state.saving ? '保存中...' : '保存并生效'}</button></div>` : `<span>${state.domains.length} 个域名</span><i></i><span>${state.forwards.length} 条转发</span><i></i><span class="green-label">${listening} 监听中</span><i></i><span>${state.diff && !state.diff.consistent ? 'hosts 待修复' : 'hosts 正常'}</span>`;
}
function validate() {
  const errors = {}; const domains = state.domains.map((item) => String(item.domain || '').trim().toLowerCase()); const listens = state.forwards.map((item) => port(item.listenPort));
  state.domains.forEach((item, index) => { const list = []; if (!String(item.domain || '').trim()) list.push('请输入域名'); if (domains[index] && domains.indexOf(domains[index]) !== index) list.push('域名重复'); if (list.length) errors[`domain:${idOf(item)}`] = list; });
  state.forwards.forEach((item, index) => { const list = []; if (!port(item.listenPort) || port(item.listenPort) > 65535) list.push('监听端口需为 1-65535'); if (!port(item.targetPort) || port(item.targetPort) > 65535) list.push('目标端口需为 1-65535'); if (!String(item.targetHost || '').trim()) list.push('请输入目标地址'); if (listens[index] && listens.indexOf(listens[index]) !== index) list.push('监听端口重复'); if (state.domains.some((domain) => String(domain.domain || '').trim().toLowerCase() === String(item.targetHost || '').trim().toLowerCase()) && item.targetHost) list.push('回环风险:目标会被解析到 127.0.0.1'); if (port(item.listenPort) > 0 && port(item.listenPort) < 1024) list.push('特权端口:可能需要管理员权限'); if (list.length) errors[`forward:${idOf(item)}`] = list; });
  state.rowErrors = errors; return Object.values(errors).some((list) => list.some((error) => !error.startsWith('回环风险') && !error.startsWith('特权端口')));
}
function focusAfterRender(key, field) { if (!key || !field) return; const input = document.querySelector(`[data-id="${CSS.escape(key)}"][data-field="${field}"]`); if (input) { input.focus(); input.setSelectionRange?.(input.value.length, input.value.length); } }
function updateItem(target) { const type = target.closest('.edit-row')?.dataset.type; const item = (type === 'domain' ? state.domains : state.forwards).find((entry) => idOf(entry) === target.dataset.id); if (!item) return; item[target.dataset.field] = target.type === 'checkbox' ? target.checked : (target.type === 'number' ? port(target.value) : target.value); if (type === 'forward' && target.dataset.field === 'targetPort') item.__targetPortEdited = true; if (type === 'forward' && target.dataset.field === 'listenPort' && !item.__targetPortEdited) item.targetPort = port(target.value); updateDirty(); validate(); render(); }
function addDomain() { const item = { domain: '', __draftId: `domain-${Date.now()}` }; state.domains.push(item); updateDirty(); render(); focusAfterRender(idOf(item), 'domain'); }
function addForward() { const item = { listenPort: 0, targetHost: '', targetPort: 0, enabled: true, status: { state: 'stopped' }, __draftId: `forward-${Date.now()}` }; state.forwards.push(item); updateDirty(); render(); focusAfterRender(idOf(item), 'listenPort'); }
function deleteItem(type, id) { const list = type === 'domain' ? state.domains : state.forwards; const item = list.find((entry) => idOf(entry) === String(id)); if (!item) return; confirmDialog(`确定删除“${type === 'domain' ? item.domain || '这个域名' : `${item.targetHost || '这个目标'}:${item.targetPort || ''}`}”吗？`, () => { if (type === 'domain') state.domains = state.domains.filter((entry) => idOf(entry) !== String(id)); else state.forwards = state.forwards.filter((entry) => idOf(entry) !== String(id)); updateDirty(); validate(); render(); }); }
function confirmDialog(message, callback, danger = true) { document.querySelector('#overlay-root').innerHTML = `<div class="overlay"><section class="confirm modal"><h2>确认操作</h2><p>${esc(message)}</p><footer class="modal-footer"><button class="button secondary" data-action="close-modal">取消</button><button class="button ${danger ? 'danger' : 'primary'}" data-action="confirm">${danger ? '删除' : '继续'}</button></footer></section></div>`; state.confirm = callback; }
async function refresh() { try { const [domains, forwards, diff, settings] = await Promise.all([ListDomains(), ListForwards(), GetStartupDiff(), GetSettings()]); state.diff = diff; state.settings = settings; if (!state.dirty) { state.appliedDomains = copy(domains || []); state.domains = copy(domains || []); state.appliedForwards = copy((forwards || []).map((item) => ({ ...(item.forward || item), status: item.status, __targetPortEdited: true }))); state.forwards = copy(state.appliedForwards); } render(); } catch (error) { console.error(error); toast('暂时无法读取接管配置', 'error'); } finally { state.loading = false; } }
async function applyDraft() { if (state.saving || !state.dirty || validate()) { render(); if (validate()) toast('请先修正标红的内容', 'error'); return; } state.saving = true; render(); try { const result = await SaveAll({ domains: state.domains.map(domainDTO), forwards: state.forwards.map(forwardDTO) }); if (result?.authCancelled) toast('未生效,需要密码才能修改 hosts', 'error'); else if (result?.validationError) toast(result.validationError, 'error'); else if (result?.otherError) toast(result.otherError, 'error'); else { state.dirty = false; toast('已保存并生效', 'success'); await refresh(); } } catch (error) { console.error(error); toast('保存失败', 'error'); } finally { state.saving = false; render(); } }
function closeOverlay() { document.querySelector('#overlay-root').innerHTML = ''; state.confirm = null; }
function openQuitConfirm() {
  state.confirm = null;
  state.quitting = false;
  document.querySelector('#overlay-root').innerHTML = `<div class="overlay"><section class="modal quit-modal" role="dialog" aria-modal="true" aria-labelledby="quit-title" aria-describedby="quit-description"><div class="quit-content"><h2 id="quit-title">域名仍在托管</h2><p id="quit-description">直接退出会停止端口转发,但 hosts 里的域名劫持会保留,之后访问这些域名会失败。建议暂停托管后再退出。</p></div><footer class="modal-footer quit-actions"><button class="button secondary quit-cancel" data-action="quit-cancel">取消</button><button class="button danger quit-direct" data-action="quit-direct">直接退出</button><button class="button primary quit-recommended" data-action="quit-pause">暂停托管并退出</button></footer></section></div>`;
  document.querySelector('.quit-recommended')?.focus();
}
async function confirmQuit(pauseFirst) {
  if (state.quitting) return;
  state.quitting = true;
  let completed = false;
  const buttons = document.querySelectorAll('.quit-modal button');
  buttons.forEach((button) => { button.disabled = true; });
  try {
    if (pauseFirst) {
      const paused = await Pause();
      if (paused?.authCancelled) { toast('未生效,需要密码才能修改 hosts', 'error'); return; }
      if (paused?.ok !== true) { toast(paused?.error || '暂停托管失败', 'error'); return; }
    }
    const result = await QuitHost();
    if (result?.ok === true) completed = true;
    else toast(result?.error || '退出失败', 'error');
  } catch (error) {
    console.error(error);
    toast('退出失败', 'error');
  } finally {
    if (!completed) {
      state.quitting = false;
      buttons.forEach((button) => { button.disabled = false; });
    }
  }
}
function setting(key, label) { return `<label class="setting"><input type="checkbox" data-setting="${key}" ${state.settings[key] ? 'checked' : ''}><span>${label}</span></label>`; }
function autostartSetting() { const value = state.settings.autoStartState; return `<label class="setting"><input type="checkbox" data-autostart="1" ${value === 'enabled' ? 'checked' : ''}><span>开机自动启动</span></label>${value === 'requires_approval' ? '<em class="field-error">未生效:请在 系统设置 → 通用 → 登录项 中批准 IntraFlow</em>' : ''}`; }
async function openSettings() { state.settings = await GetSettings(); state.hostsZone = await CurrentHostsZone(); state.settings.autoStartState ??= 'disabled'; document.querySelector('#overlay-root').innerHTML = `<div class="overlay settings-overlay"><section class="modal settings-modal" role="dialog" aria-modal="true"><div class="modal-heading"><h2>设置</h2><button class="icon-button" data-action="close-modal" aria-label="关闭">×</button></div><div class="settings-body"><section><h3>启动</h3>${autostartSetting()}</section><section><h3>运行</h3><label class="setting-number">DNS 刷新间隔(分钟)<input id="dns-refresh" type="text" inputmode="numeric" pattern="[0-9]*" min="1" max="60" value="${esc(state.settings.dnsRefreshMinutes || 5)}"><em id="dns-save-state" class="save-state" aria-live="polite"></em></label></section><section><h3>hosts 管理</h3><pre class="hosts-zone">${esc(state.hostsZone)}</pre><div class="settings-actions"><button class="button secondary" data-action="export">导出当前接管区</button><button class="button secondary" data-action="clean">清理残留</button></div></section><section class="about"><h3>关于</h3><p>IntraFlow v0.1.1</p></section></div></section></div>`; }
function scheduleDnsSave(input) { const message = document.querySelector('#dns-save-state'); const minutes = Number(input.value); if (!Number.isInteger(minutes) || minutes < 1 || minutes > 60) { if (message) { message.textContent = '请输入 1-60'; message.className = 'save-state invalid'; } clearTimeout(state.dnsSaveTimer); return; } if (message) { message.textContent = '保存中...'; message.className = 'save-state'; } clearTimeout(state.dnsSaveTimer); state.dnsSaveTimer = setTimeout(async () => { const result = await SetSettings({ paused: !!state.settings.paused, dnsRefreshMinutes: minutes }); if (result?.ok === false) { if (message) { message.textContent = result.error || '保存失败'; message.className = 'save-state invalid'; } } else { state.settings.dnsRefreshMinutes = minutes; if (message) { message.textContent = '已保存'; message.className = 'save-state saved'; } setTimeout(() => { if (message?.textContent === '已保存') message.textContent = ''; }, 1600); } }, 400); }
function exportHosts() { const blob = new Blob([state.hostsZone], { type: 'text/plain;charset=utf-8' }); const link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = 'intraflow-hosts.txt'; link.click(); URL.revokeObjectURL(link.href); }
async function togglePause(action) { const result = await (action === 'pause' ? Pause() : Resume()); if (result?.authCancelled) toast('未生效,需要密码才能修改 hosts', 'error'); else if (result?.ok === false) toast(result.error || '操作失败', 'error'); else { state.settings.paused = action === 'pause'; toast(action === 'pause' ? '已暂停托管' : '已恢复托管', 'success'); await refresh(); } }

document.addEventListener('click', async (event) => { const target = event.target.closest('[data-action]'); if (!target) return; const action = target.dataset.action; if (action === 'add-domain') addDomain(); else if (action === 'add-forward') addForward(); else if (action === 'delete-domain') deleteItem('domain', target.dataset.id); else if (action === 'delete-forward') deleteItem('forward', target.dataset.id); else if (action === 'settings') openSettings(); else if (action === 'close-modal') closeOverlay(); else if (action === 'confirm') { const cb = state.confirm; closeOverlay(); await cb?.(); } else if (action === 'apply') await applyDraft(); else if (action === 'discard') { state.dirty = false; state.rowErrors = {}; await refresh(); } else if (action === 'pause' || action === 'resume') await togglePause(action); else if (action === 'fix') { const result = await FixNow(); if (result?.authCancelled) toast('未生效,需要密码才能修改 hosts', 'error'); else if (result?.ok !== false) { toast('hosts 已修复', 'success'); await refresh(); } } else if (action === 'suggest-port') { const item = state.forwards.find((entry) => idOf(entry) === target.dataset.id); if (item) { item.listenPort = Number(target.dataset.port); state.portIssues[idOf(item)] = null; updateDirty(); render(); focusAfterRender(idOf(item), 'listenPort'); } } else if (action === 'save-settings') { const minutes = port(document.querySelector('#dns-refresh')?.value); if (minutes < 1 || minutes > 60) return toast('DNS 刷新间隔需为 1-60 分钟', 'error'); const result = await SetSettings({ paused: !!state.settings.paused, dnsRefreshMinutes: minutes }); if (result?.ok === false) toast(result.error || '设置保存失败', 'error'); else { toast('已保存', 'success'); closeOverlay(); } } else if (action === 'export') exportHosts(); else if (action === 'clean') confirmDialog('将以配置为准重写 hosts 标记区,需要管理员密码。继续?', async () => { const result = await FixNow(); if (result?.authCancelled) toast('未生效,需要密码才能修改 hosts', 'error'); else if (result?.ok !== false) { toast('hosts 已清理', 'success'); await openSettings(); } }, false); });
document.addEventListener('input', (event) => { if (event.target.matches('.row-input')) updateItem(event.target); else if (event.target.matches('#dns-refresh')) scheduleDnsSave(event.target); });
document.addEventListener('keydown', (event) => { if (event.key !== 'Enter' || !event.target.matches('.row-input')) return; const row = event.target.closest('.edit-row'); if (!row || event.target.dataset.field !== (row.dataset.type === 'domain' ? 'domain' : 'targetPort')) return; event.preventDefault(); if (row.dataset.type === 'domain') addDomain(); else addForward(); });
document.addEventListener('change', async (event) => { const target = event.target; if (target.dataset.autostart) { const previous = state.settings.autoStartState; state.settings.autoStartState = target.checked ? 'enabled' : 'disabled'; const result = await SetAutoStart(target.checked); if (!result || result.ok === false) { state.settings.autoStartState = previous; toast(result?.error || '设置开机自启失败', 'error'); } await openSettings(); return; } if (target.matches('.forward-row input[type="checkbox"]')) updateItem(target); });
document.addEventListener('blur', async (event) => { if (!event.target.matches('[data-field="listenPort"]')) return; const item = state.forwards.find((entry) => idOf(entry) === event.target.dataset.id); const value = port(item?.listenPort); if (!value) return; try { if (await CheckPortAvailable(value)) state.portIssues[idOf(item)] = null; else { state.portIssues[idOf(item)] = { port: value, suggested: await SuggestFreePort(value) }; toast(`端口 ${value} 已被占用,建议 ${state.portIssues[idOf(item)].suggested}`, 'error'); } render(); } catch (error) { console.error(error); } });
document.addEventListener('click', (event) => {
  const action = event.target.closest('[data-action]')?.dataset.action;
  if (action === 'quit-cancel' && !state.quitting) closeOverlay();
  else if (action === 'quit-pause') confirmQuit(true);
  else if (action === 'quit-direct') confirmQuit(false);
});
document.addEventListener('keydown', (event) => {
  if (event.key === 'Escape' && document.querySelector('.quit-modal') && !state.quitting) closeOverlay();
});
shell(); render(); EventsOn('recordsChanged', () => { if (!state.dirty) refresh(); }); EventsOn('openSettings', () => openSettings()); EventsOn('confirmQuit', openQuitConfirm); EventsOn('focusWindow', () => { WindowUnminimise(); WindowShow(); }); refresh(); PendingAction().then((action) => { if (action === 'settings') openSettings(); else if (action === 'confirmQuit') openQuitConfirm(); });
