// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckPortAvailable(arg1) {
  return window['go']['main']['App']['CheckPortAvailable'](arg1);
}

export function CurrentHostsZone() {
  return window['go']['main']['App']['CurrentHostsZone']();
}

export function FixNow() {
  return window['go']['main']['App']['FixNow']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetStartupDiff() {
  return window['go']['main']['App']['GetStartupDiff']();
}

export function IsPrivilegedPort(arg1) {
  return window['go']['main']['App']['IsPrivilegedPort'](arg1);
}

export function ListDomains() {
  return window['go']['main']['App']['ListDomains']();
}

export function ListForwards() {
  return window['go']['main']['App']['ListForwards']();
}

export function Pause() {
  return window['go']['main']['App']['Pause']();
}

export function PendingAction() {
  return window['go']['main']['App']['PendingAction']();
}

export function QuitHost() {
  return window['go']['main']['App']['QuitHost']();
}

export function Resume() {
  return window['go']['main']['App']['Resume']();
}

export function SaveAll(arg1) {
  return window['go']['main']['App']['SaveAll'](arg1);
}

export function SetAutoStart(arg1) {
  return window['go']['main']['App']['SetAutoStart'](arg1);
}

export function SetSettings(arg1) {
  return window['go']['main']['App']['SetSettings'](arg1);
}

export function SuggestFreePort(arg1) {
  return window['go']['main']['App']['SuggestFreePort'](arg1);
}
