// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {ipc} from '../models';

export function CheckPortAvailable(arg1:number):Promise<boolean>;

export function CurrentHostsZone():Promise<string>;

export function FixNow():Promise<ipc.SimpleResult>;

export function GetSettings():Promise<ipc.SettingsDTO>;

export function GetStartupDiff():Promise<ipc.DiffDTO>;

export function IsPrivilegedPort(arg1:number):Promise<boolean>;

export function ListDomains():Promise<Array<ipc.DomainDTO>>;

export function ListForwards():Promise<Array<ipc.ForwardStatusDTO>>;

export function Pause():Promise<ipc.SimpleResult>;

export function PendingAction():Promise<string>;

export function QuitHost():Promise<ipc.SimpleResult>;

export function Resume():Promise<ipc.SimpleResult>;

export function SaveAll(arg1:ipc.SaveAllPayload):Promise<ipc.SaveResultDTO>;

export function SetAutoStart(arg1:boolean):Promise<ipc.SimpleResult>;

export function SetSettings(arg1:ipc.SettingsDTO):Promise<ipc.SimpleResult>;

export function SuggestFreePort(arg1:number):Promise<number>;
